[2025-09-06T07:31:21.491+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T07:31:21.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops_w8_pipeline.train manual__2025-09-06T07:29:44+00:00 [queued]>
[2025-09-06T07:31:21.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops_w8_pipeline.train manual__2025-09-06T07:29:44+00:00 [queued]>
[2025-09-06T07:31:21.538+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-06T07:31:21.550+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): train> on 2025-09-06 07:29:44+00:00
[2025-09-06T07:31:21.556+0000] {standard_task_runner.py:64} INFO - Started process 223 to run task
[2025-09-06T07:31:21.560+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mlops_w8_pipeline', 'train', 'manual__2025-09-06T07:29:44+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpn7wurjgo']
[2025-09-06T07:31:21.562+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask train
[2025-09-06T07:31:21.627+0000] {task_command.py:426} INFO - Running <TaskInstance: mlops_w8_pipeline.train manual__2025-09-06T07:29:44+00:00 [running]> on host c8f8d8a0876c
[2025-09-06T07:31:21.899+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='samarth' AIRFLOW_CTX_DAG_ID='mlops_w8_pipeline' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T07:29:44+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T07:29:44+00:00'
[2025-09-06T07:31:21.899+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T07:31:21.900+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T07:31:21.900+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 33, in train
    from src.train_eval import train_model
ModuleNotFoundError: No module named 'src'
[2025-09-06T07:31:21.915+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_w8_pipeline, task_id=train, run_id=manual__2025-09-06T07:29:44+00:00, execution_date=20250906T072944, start_date=20250906T073121, end_date=20250906T073121
[2025-09-06T07:31:21.926+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task train (No module named 'src'; 223)
[2025-09-06T07:31:21.973+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-06T07:31:22.178+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T07:31:22.180+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
